version: '3'

services:
  kafka:
    image: spotify/kafka
    container_name: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ADVERTISED_PORT=9092
      - ADVERTISED_HOST=localhost
